'use client';

import {Alert,Button,Card,Checkbox,Field,TextInput} from '@/components/design-system';
import {SplitParticipantRow} from '@/components/patterns';
import type {MiraMode} from '@/components/design-system/tokens';

type SplitItem={id:string;label:string;remaining:string;disabled:boolean;selected:boolean};
type Participant={name:string;amount:string;paid:string;remaining:string;status:'success'|'warning'|'error'|'info'|'neutral'|'pending';selected?:boolean};
export function GuestSplitScreen({mode,items,participants,customAmount,busy,error,onToggleItem,onMode,onCustomAmount,onCustomSubmit}:{mode:MiraMode;items:SplitItem[];participants:Participant[];customAmount:string;busy:boolean;error?:string;onToggleItem:(id:string,checked:boolean)=>void;onMode:(mode:'own'|'items'|'equal'|'all')=>void;onCustomAmount:(value:string)=>void;onCustomSubmit:()=>void}){return <section className="guest-screen-stack"><Card mode={mode} className="guest-mobile-card"><h3>Разделение счёта</h3><p>Выберите позиции или способ оплаты. Расчёт выполняет текущий сервис счёта.</p>{error&&<Alert mode={mode} status="error" title="Не удалось выбрать часть счёта">{error}</Alert>}</Card>{participants.map(p=><SplitParticipantRow key={p.name} mode={mode} {...p}/>) }<Card mode={mode} className="guest-mobile-card"><h3>Позиции заказа</h3>{items.map(item=><Checkbox key={item.id} mode={mode} label={<span>{item.label}<small className="block">Остаток {item.remaining}</small></span>} checked={item.selected} disabled={item.disabled||busy} onCheckedChange={checked=>onToggleItem(item.id,checked===true)}/>)}</Card><Card mode={mode} className="guest-mobile-card guest-split-method-card"><h3>Способ разделения</h3><div className="guest-inline-actions"><Button mode={mode} size="l" variant="secondary" disabled={busy} onClick={()=>onMode('own')}>Свои позиции</Button><Button mode={mode} size="l" variant="secondary" disabled={busy} onClick={()=>onMode('items')}>По блюдам</Button><Button mode={mode} size="l" variant="secondary" disabled={busy} onClick={()=>onMode('equal')}>Поровну</Button><Button mode={mode} size="l" variant="secondary" disabled={busy} onClick={()=>onMode('all')}>Оплатить весь остаток</Button></div><div className="guest-amount-selection"><Field mode={mode} label="Указанная сумма, ₽"><TextInput mode={mode} type="number" min="0" value={customAmount} onChange={e=>onCustomAmount(e.target.value)}/></Field><Button mode={mode} size="l" disabled={busy} onClick={onCustomSubmit}>Выбрать сумму</Button></div></Card></section>}
