'use client';

import {Alert,Button,EmptyState,IconButton} from '@/components/design-system';
import {ProductListItem} from '@/components/patterns';
import type {MiraMode} from '@/components/design-system/tokens';
import {Minus,Plus,Trash2} from 'lucide-react';

type CartLine={id:string;title:string;metadata:string;price:string;quantity:number;unavailable:boolean};
export function GuestCartScreen({mode,items,total,busy,submitted,onOpenMenu,onDecrease,onIncrease,onRemove,onSubmit}:{mode:MiraMode;items:CartLine[];total:string;busy:boolean;submitted:boolean;onOpenMenu:()=>void;onDecrease:(id:string)=>void;onIncrease:(id:string)=>void;onRemove:(id:string)=>void;onSubmit:()=>void}){if(!items.length)return <section className="guest-screen-stack">{submitted&&<Alert mode={mode} status="success" title="Заказ отправлен">Статус приготовления появится здесь.</Alert>}<EmptyState mode={mode} title="Корзина пока пуста" description="Добавьте что-нибудь из меню." primaryAction={<Button mode={mode} onClick={onOpenMenu}>Открыть меню</Button>}/></section>;return <section className="guest-screen-stack"><h2>Ваш заказ</h2>{submitted&&<Alert mode={mode} status="success" title="Заказ отправлен">Статус приготовления появится здесь.</Alert>}<div className="guest-cart-lines">{items.map(item=><ProductListItem key={item.id} mode={mode} title={item.title} metadata={item.metadata} price={item.price} quantity={item.quantity} availability={item.unavailable?'unavailable':'available'} trailingAction={<span className="guest-inline-actions"><IconButton mode={mode} variant="secondary" aria-label={`Уменьшить: ${item.title}`} disabled={item.quantity<=1||busy} onClick={()=>onDecrease(item.id)}><Minus/></IconButton><IconButton mode={mode} variant="secondary" aria-label={`Увеличить: ${item.title}`} disabled={item.quantity>=99||busy} onClick={()=>onIncrease(item.id)}><Plus/></IconButton><IconButton mode={mode} variant="ghost" aria-label={`Убрать: ${item.title}`} disabled={busy} onClick={()=>onRemove(item.id)}><Trash2/></IconButton></span>}/>)}</div><div className="guest-total"><strong>Итого</strong><strong>{total}</strong></div><Button mode={mode} size="l" fullWidth loading={busy} onClick={onSubmit}>Оформить заказ</Button></section>}
