"use client"
import * as React from "react"
import {Heart,MapPin,Receipt,Users,UtensilsCrossed} from "lucide-react"
import {Badge,Button,Card,IconButton,StatusBadge} from "@/components/design-system"
import type {MiraMode} from "@/components/design-system/tokens"
import s from "./patterns.module.css"
type Tone="success"|"warning"|"error"|"info"|"neutral"|"pending"; type Base={mode?:MiraMode};
const Media=({ratio="4 / 3",label}:{ratio?:string;label:string})=><div className={s.media} style={{aspectRatio:ratio}} role="img" aria-label={label}/>
export function ProductCard({image,title,description,price,oldPrice,badge,availability="available",quantity,actionLabel="Добавить",onAction,onFavourite,mode}:Base&{image?:string;title:string;description:string;price:string;oldPrice?:string;badge?:string;availability?:"available"|"unavailable";quantity?:number;actionLabel?:string;onAction?:()=>void;onFavourite?:()=>void}){return <Card mode={mode} className={s.productCard} style={{gridTemplateColumns:"minmax(0,1fr)"}}>{image?<img className={s.media} style={{aspectRatio:"4 / 3"}} src={image} alt=""/>:<Media label={title}/>}<div className={s.cardBody} style={{gridTemplateColumns:"minmax(0,1fr)",minWidth:0}}>{badge&&<Badge mode={mode}>{badge}</Badge>}{onFavourite&&<IconButton mode={mode} aria-label={`В избранное: ${title}`} onClick={onFavourite}><Heart/></IconButton>}<h3>{title}</h3><p>{description}</p><div className={s.price}><strong>{price}</strong>{oldPrice&&<s>{oldPrice}</s>}</div>{quantity!==undefined&&<span>В корзине: {quantity}</span>}<Button mode={mode} size="l" fullWidth style={{paddingInline:8,minWidth:0}} disabled={availability==="unavailable"} onClick={onAction}>{availability==="unavailable"?"Недоступно":actionLabel}</Button></div></Card>}
export function ProductListItem({title,metadata,price,quantity,availability="available",trailingAction,mode}:Base&{title:string;metadata:string;price:string;quantity?:number;availability?:"available"|"unavailable";trailingAction?:React.ReactNode}){return <Card mode={mode} className={s.listRow}><Media ratio="1 / 1" label={title}/><div><strong>{title}</strong><p>{metadata}</p>{quantity!==undefined&&<span>× {quantity}</span>}</div><div><strong>{price}</strong>{availability==="unavailable"&&<span>Стоп-лист</span>}{trailingAction}</div></Card>}
export function VenueCard({name,cuisine,rating,distance,meta,badge,open=true,onAction,mode}:Base&{name:string;cuisine:string;rating?:string;distance?:string;meta?:string;badge?:string;open?:boolean;onAction?:()=>void}){return <Card mode={mode} className={s.discovery}><Media ratio="16 / 9" label={name}/><div className={s.cardBody}>{badge&&<Badge mode={mode}>{badge}</Badge>}<h3>{name}</h3><p>{cuisine}</p><p>{rating} · {distance} · {meta}</p><StatusBadge mode={mode} status={open?"success":"neutral"}>{open?"Открыто":"Закрыто"}</StatusBadge>{onAction&&<Button mode={mode} size="l" variant="secondary" onClick={onAction}>Открыть</Button>}</div></Card>}
export function EventCard({title,venue,dateTime,category,note,onAction,mode}:Base&{title:string;venue:string;dateTime:string;category:string;note?:string;onAction?:()=>void}){return <Card mode={mode} className={s.discovery}><Media ratio="16 / 9" label={title}/><div className={s.cardBody}><Badge mode={mode}>{category}</Badge><h3>{title}</h3><p>{venue} · {dateTime}</p>{note&&<p>{note}</p>}{onAction&&<Button mode={mode} size="l" variant="secondary" onClick={onAction}>Подробнее</Button>}</div></Card>}
export function PromotionCard({title,description,venue,validity,badge="Акция",onAction,mode}:Base&{title:string;description:string;venue?:string;validity:string;badge?:string;onAction?:()=>void}){return <Card mode={mode} className={s.discovery}><Media ratio="16 / 9" label={title}/><div className={s.cardBody}><Badge mode={mode}>{badge}</Badge><h3>{title}</h3><p>{description}</p><p>{venue} · {validity}</p>{onAction&&<Button mode={mode} size="l" onClick={onAction}>Узнать условия</Button>}</div></Card>}
export function OrderCard({identifier,context,itemCount,amount,status,timestamp,primaryAction,secondaryAction,mode}:Base&{identifier:string;context:string;itemCount:string;amount:string;status:Tone;timestamp?:string;primaryAction?:React.ReactNode;secondaryAction?:React.ReactNode}){return <Card mode={mode} className={s.summary}><div><h3>{identifier}</h3><p>{context} · {itemCount}</p>{timestamp&&<p>{timestamp}</p>}</div><div><strong>{amount}</strong><StatusBadge mode={mode} status={status}>{status}</StatusBadge></div><div className={s.actions}>{primaryAction}{secondaryAction}</div></Card>}
export function BillSummary({lines,subtotal,discounts,bonuses,total,paid,remaining,actions,mode}:Base&{lines:{label:string;value:string}[];subtotal:string;discounts?:string;bonuses?:string;total:string;paid?:string;remaining?:string;actions?:React.ReactNode}){return <Card mode={mode} className={s.bill}>{lines.map(x=><div key={x.label}><span>{x.label}</span><span>{x.value}</span></div>)}<div><span>Подытог</span><span>{subtotal}</span></div>{discounts&&<div><span>Скидка</span><span>{discounts}</span></div>}{bonuses&&<div><span>Бонусы</span><span>{bonuses}</span></div>}<div className={s.total}><strong>Итого</strong><strong>{total}</strong></div>{paid&&<div><span>Оплачено</span><span>{paid}</span></div>}{remaining&&<div><span>Осталось</span><span>{remaining}</span></div>}{actions&&<div className={s.actions}>{actions}</div>}</Card>}
export function SplitParticipantRow({name,amount,paid,remaining,status,selected,onAction,mode}:Base&{name:string;amount:string;paid:string;remaining:string;status:Tone;selected?:boolean;onAction?:()=>void}){return <Card mode={mode} variant={selected?"selected":"default"} className={s.split}><Users/><div><strong>{name}</strong><p>Назначено: {amount}</p></div><div><span>Оплачено: {paid}</span><strong>Осталось: {remaining}</strong><StatusBadge mode={mode} status={status}>{status}</StatusBadge></div>{onAction&&<Button mode={mode} variant="ghost" onClick={onAction}>Выбрать</Button>}</Card>}
export function TableCard({table,zone,guests,session,orderStatus,calls,bill,selected,onAction,mode}:Base&{table:string;zone:string;guests:string;session:string;orderStatus:string;calls?:string;bill?:string;selected?:boolean;onAction?:()=>void}){return <Card mode={mode} variant={selected?"selected":"default"} className={s.table}><UtensilsCrossed/><h3>{table}</h3><p>{zone} · {guests}</p><p>{session} · {orderStatus}</p>{calls&&<Badge mode={mode}>{calls}</Badge>}{bill&&<strong>{bill}</strong>}{onAction&&<Button mode={mode} variant="ghost" onClick={onAction}>Открыть</Button>}</Card>}
export function ServiceCallCard({type,table,elapsed,status,assignee,primaryAction,secondaryAction,mode}:Base&{type:string;table:string;elapsed:string;status:Tone;assignee?:string;primaryAction?:React.ReactNode;secondaryAction?:React.ReactNode}){return <Card mode={mode} className={s.summary}><div><h3>{type} · {table}</h3><p>{elapsed}{assignee&&` · ${assignee}`}</p></div><StatusBadge mode={mode} status={status}>{status}</StatusBadge><div className={s.actions}>{primaryAction}{secondaryAction}</div></Card>}
export function PaymentSummaryCard({total,paid,remaining,method,status,action,mode}:Base&{total:string;paid:string;remaining:string;method?:string;status:Tone;action?:React.ReactNode}){return <Card mode={mode} className={s.summary}><Receipt/><div><h3>Оплата</h3><p>{method}</p><p>Всего {total} · Оплачено {paid}</p><strong>Осталось: {remaining}</strong></div><StatusBadge mode={mode} status={status}>{status}</StatusBadge>{action}</Card>}
export function TipSummary({base,selected,tip,commission,finalAmount,recipient,mode}:Base&{base:string;selected?:string;tip:string;commission?:string;finalAmount:string;recipient?:string}){return <Card mode={mode} className={s.bill}><h3>Чаевые</h3><div><span>Счёт</span><span>{base}</span></div>{selected&&<div><span>Выбрано</span><span>{selected}</span></div>}<div><span>Чаевые</span><span>{tip}</span></div>{commission&&<div><span>Комиссия</span><span>{commission}</span></div>}<div className={s.total}><strong>К оплате</strong><strong>{finalAmount}</strong></div>{recipient&&<p>Получатель: {recipient}</p>}</Card>}
export function BonusSummary({available,used,accrued,help,action,mode}:Base&{available:string;used:string;accrued:string;help?:string;action?:React.ReactNode}){return <Card mode={mode} className={s.summary}><div><h3>Бонусы</h3><strong>{available}</strong><p>Использовано: {used} · Начислено: {accrued}</p>{help&&<p>{help}</p>}</div>{action}</Card>}
export function MetricCard({label,value,supporting,status,icon,action,mode}:Base&{label:string;value:string;supporting?:string;status?:Tone;icon?:React.ReactNode;action?:React.ReactNode}){return <Card mode={mode} className={s.metric}>{icon||<MapPin/>}<span>{label}</span><strong>{value}</strong>{supporting&&<p>{supporting}</p>}{status&&<StatusBadge mode={mode} status={status}>{status}</StatusBadge>}{action}</Card>}
export function SectionHeader({title,description,action,mode}:Base&{title:string;description?:string;action?:React.ReactNode}){return <header className={s.sectionHeader}><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</header>}
export function ResponsiveActionGroup({children}:{children:React.ReactNode}){return <div className={s.actions}>{children}</div>}
