"use client"

import * as React from "react"
import { Check, CircleAlert, Info, LoaderCircle, Minus, X } from "lucide-react"
import { Checkbox as CheckboxPrimitive } from "@/components/ui/checkbox"
import { Switch as SwitchPrimitive } from "@/components/ui/switch"
import { Dialog as RadixDialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog"
import { Sheet, SheetContent, SheetDescription, SheetTitle } from "@/components/ui/sheet"
import { cn } from "@/lib/utils"
import { miraTokens, type MiraMode } from "./tokens"
import styles from "./styles.module.css"

type Tone = "success" | "warning" | "error" | "info" | "neutral" | "pending"
type Size = "s" | "m" | "l"
type ModeProps = { mode?: MiraMode }
const toneIcon = { success: Check, warning: CircleAlert, error: CircleAlert, info: Info, neutral: Info, pending: LoaderCircle } as const
const modeClass = (mode: MiraMode = "brand-dark") => mode === "brand-dark" ? styles.dark : styles.light

export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & ModeProps & { variant?: "primary" | "secondary" | "ghost" | "destructive" | "link"; size?: Size; leadingIcon?: React.ReactNode; trailingIcon?: React.ReactNode; loading?: boolean; fullWidth?: boolean }
export function Button({ variant="primary", size="m", leadingIcon, trailingIcon, loading, fullWidth, mode, children, className, disabled, ...props }: ButtonProps) {
  return <button {...props} disabled={disabled || loading} aria-busy={loading || undefined} className={cn(styles.button, modeClass(mode), styles[variant], ({s:styles.sizeS,m:styles.sizeM,l:styles.sizeL})[size], fullWidth && styles.full, className)}><span className={cn(styles.buttonContent,loading && styles.hiddenLabel)}>{leadingIcon}{children}{trailingIcon}</span>{loading && <LoaderCircle className={styles.spinner} aria-hidden="true"/>}</button>
}
export function IconButton({ "aria-label": label, children, size="m", ...props }: Omit<ButtonProps,"children"|"leadingIcon"|"trailingIcon"> & {"aria-label": string; children: React.ReactNode}) { return <Button {...props} size={size} aria-label={label} className={cn(styles.iconButton, props.className)}>{children}</Button> }

export function Field({ mode, label, required, help, error, success, counter, children, className }: ModeProps & { label: string; required?: boolean; help?: React.ReactNode; error?: React.ReactNode; success?: React.ReactNode; counter?: React.ReactNode; children: React.ReactNode; className?: string }) { const id=React.useId(); const message=error ?? success ?? help; const validation=error ? styles.statuserror : success ? styles.statussuccess : undefined; return <div className={cn(styles.field, modeClass(mode), validation, className)}><label htmlFor={id}>{label}{required && <span aria-hidden="true"> *</span>}</label>{React.isValidElement(children) ? React.cloneElement(children as React.ReactElement<{id?:string;required?:boolean;"aria-required"?:boolean;"aria-describedby"?:string;"aria-invalid"?:boolean;"data-validation"?:"error"|"success"}>, {id,required: required || undefined,"aria-required":required || undefined,"aria-describedby":message ? `${id}-message` : undefined,"aria-invalid":Boolean(error),"data-validation":error ? "error" : success ? "success" : undefined}) : children}{message && <div id={`${id}-message`} className={cn(styles.message,error ? styles.validationError : success ? styles.validationSuccess : styles.validationHelp)}>{message}</div>}{counter && <div className={styles.counter}>{counter}</div>}</div> }
export const TextInput = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement> & ModeProps & {leading?:React.ReactNode; trailing?:React.ReactNode}>(({leading,trailing,mode,className,...props},ref)=><div className={cn(styles.inputWrap,modeClass(mode),className)}>{leading}<input ref={ref} className={styles.input} {...props}/>{trailing}</div>); TextInput.displayName="TextInput"
export const Textarea = React.forwardRef<HTMLTextAreaElement, React.TextareaHTMLAttributes<HTMLTextAreaElement> & ModeProps>(({mode,className,...props},ref)=><textarea ref={ref} className={cn(styles.textarea,modeClass(mode),className)} {...props}/>); Textarea.displayName="Textarea"

export function Checkbox({mode,label,indeterminate=false,className,checked,defaultChecked,onCheckedChange,onChange,disabled,...props}:ModeProps & {label:React.ReactNode;indeterminate?:boolean;checked?:boolean;defaultChecked?:boolean;onCheckedChange?:(checked:boolean|"indeterminate")=>void;onChange?:(event:{target:{checked:boolean}})=>void;disabled?:boolean;className?:string} & Omit<React.ComponentProps<typeof CheckboxPrimitive>,"checked"|"defaultChecked"|"onCheckedChange"|"onChange"|"disabled"|"className">){const handleChange=(value:boolean|"indeterminate")=>{onCheckedChange?.(value);onChange?.({target:{checked:value===true}})};return <label className={cn(styles.choice,modeClass(mode),disabled&&styles.disabledChoice,className)}><CheckboxPrimitive {...props} checked={indeterminate?"indeterminate":checked} defaultChecked={defaultChecked} disabled={disabled} onCheckedChange={handleChange} className={cn(styles.checkControl,props["aria-invalid"]&&styles.invalidControl)}>{indeterminate?<Minus aria-hidden="true"/>:<Check aria-hidden="true"/>}</CheckboxPrimitive><span>{label}</span></label>}
export function Radio({ mode, label, className, ...props }: React.InputHTMLAttributes<HTMLInputElement> & ModeProps & {label:React.ReactNode}) { return <label className={cn(styles.choice,modeClass(mode),props.disabled&&styles.disabledChoice,className)}><input className={cn(styles.radioControl,props["aria-invalid"]&&styles.invalidControl)} type="radio" {...props}/><span>{label}</span></label> }
export function Switch({ mode, checked, onCheckedChange, label, disabled }: ModeProps & {checked:boolean; onCheckedChange:(checked:boolean)=>void; label:string; disabled?:boolean}) { return <label className={cn(styles.choice,modeClass(mode),disabled&&styles.disabledChoice)}><SwitchPrimitive checked={checked} disabled={disabled} onCheckedChange={onCheckedChange} className={styles.switch}><span className={styles.switchThumb}/></SwitchPrimitive><span>{label}</span></label> }
export function Chip({ mode, selected, removable, onRemove, removeLabel="Удалить", disabled, className, children, onClick, ...props }: ModeProps & {selected?:boolean; removable?:boolean; onRemove?:()=>void; removeLabel?:string; disabled?:boolean; className?:string; children:React.ReactNode; onClick?:React.MouseEventHandler<HTMLButtonElement>}) { return <span className={cn(styles.chip,modeClass(mode),selected && styles.chipSelected,disabled&&styles.disabledChoice,className)}><button type="button" aria-pressed={selected} disabled={disabled} onClick={onClick} {...props}>{children}</button>{removable && onRemove && <button type="button" aria-label={removeLabel} disabled={disabled} onClick={onRemove}><X aria-hidden="true"/></button>}</span> }

export function Card({ mode, variant="default", children, className, ...props }: React.HTMLAttributes<HTMLDivElement> & ModeProps & {variant?:"default"|"interactive"|"selected"|"raised"}) { return <div {...props} className={cn(styles.card,modeClass(mode),variant==="selected"&&styles.cardSelected,variant==="raised"&&styles.raised,variant==="interactive"&&styles.interactive,className)}>{children}</div> }
export function Badge({ mode, children, className }: React.PropsWithChildren<ModeProps & {className?:string}>) { return <span className={cn(styles.badge,modeClass(mode),className)}>{children}</span> }
export function StatusBadge({ mode, status, children }: ModeProps & {status:Tone; children:React.ReactNode}) { const Icon=toneIcon[status]; return <span className={cn(styles.status,modeClass(mode),styles[`status${status}`])}><Icon aria-hidden="true"/>{children}</span> }

export function Alert({ mode, status="info", title, children, onDismiss, action }: ModeProps & {status?:Exclude<Tone,"pending">; title:string; children?:React.ReactNode; onDismiss?:()=>void; action?:React.ReactNode}) { const Icon=toneIcon[status]; return <section className={cn(styles.alert,modeClass(mode),styles[`status${status}`])}><Icon aria-hidden="true"/><div><strong>{title}</strong>{children && <div>{children}</div>}{action}</div>{onDismiss && <button aria-label="Закрыть" onClick={onDismiss}><X/></button>}</section> }
export function Toast({ mode, status="info", title, children, onClose, action }: ModeProps & {status?:Exclude<Tone,"neutral"|"pending">; title:string; children?:React.ReactNode; onClose?:()=>void; action?:React.ReactNode}) { const live=status==="error"||status==="warning"?"alert":"status"; return <section role={live} className={cn(styles.toast,modeClass(mode),styles[`status${status}`])}><Alert mode={mode} status={status} title={title} onDismiss={onClose} action={action}>{children}</Alert></section> }

export function Dialog({ mode="brand-dark", open, onOpenChange, title, description, children, actions }: ModeProps & {open:boolean;onOpenChange:(open:boolean)=>void;title:string;description?:string;children:React.ReactNode;actions?:React.ReactNode}) { return <RadixDialog open={open} onOpenChange={onOpenChange}><DialogContent overlayStyle={{background:miraTokens.backdrop[mode]}} className={cn(styles.dialog,modeClass(mode))}><DialogTitle>{title}</DialogTitle>{description && <DialogDescription>{description}</DialogDescription>}<div className={styles.dialogBody}>{children}</div>{actions && <div className={styles.actions}>{actions}</div>}</DialogContent></RadixDialog> }
export function BottomSheet({ mode="brand-dark", open, onOpenChange, title, description, children, actions, presentation="bottom-sheet", className, style, overlayStyle }: ModeProps & {open:boolean;onOpenChange:(open:boolean)=>void;title:string;description?:string;children:React.ReactNode;actions?:React.ReactNode;presentation?:"bottom-sheet"|"responsive-dialog";className?:string;style?:React.CSSProperties;overlayStyle?:React.CSSProperties}) { return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="bottom" overlayStyle={overlayStyle??{background:miraTokens.backdrop[mode]}} style={{...style,"--mira-touch-target":miraTokens.control.hitAreaMin} as React.CSSProperties} className={cn(styles.sheet,modeClass(mode),presentation==="responsive-dialog"&&styles.responsiveDialog,className)}><SheetTitle>{title}</SheetTitle>{description && <SheetDescription>{description}</SheetDescription>}<div className={styles.dialogBody}>{children}</div>{actions && <div className={styles.actions}>{actions}</div>}</SheetContent></Sheet> }

export function Skeleton({ mode, variant="block", className }: ModeProps & {variant?:"text"|"avatar"|"media"|"block"|"card-shell";className?:string}) { return <div aria-label="Загрузка" className={cn(styles.skeleton,styles[`skeleton${variant}`],modeClass(mode),className)}/> }
export function EmptyState({ mode, icon, title, description, primaryAction, secondaryAction, headingLevel }: ModeProps & {icon?:React.ReactNode;title:string;description:string;primaryAction?:React.ReactNode;secondaryAction?:React.ReactNode;headingLevel?:2|3|4|5|6}) { const Heading=headingLevel ? (`h${headingLevel}` as keyof React.JSX.IntrinsicElements) : "div"; return <section className={cn(styles.empty,modeClass(mode))}>{icon}<Heading className={styles.emptyTitle}>{title}</Heading><p>{description}</p><div className={styles.actions}>{primaryAction}{secondaryAction}</div></section> }
