import {test,expect} from '@playwright/test';
import {openWaiterWorkspace} from './waiter-helper';

test('all sixteen dishes have local photos and recipes in Guest, Waiter and Admin',async({page,request})=>{
 test.setTimeout(90000);
 for(let i=1;i<=16;i++){const response=await request.get(i===1?'/images/burrata.png':`/images/menu/p${i}.png`);expect(response.ok()).toBe(true);expect(response.headers()['content-type']).toContain('image/')}
 await page.goto('/demo/guest/home');await page.getByRole('button',{name:'Сканировать QR стола №12',exact:true}).click();await page.getByRole('button',{name:'Меню',exact:true}).click();await expect(page.locator('.guest-content img[src^="/images/menu/"], .guest-content img[src="/images/burrata.png"]')).toHaveCount(16);
 await page.getByRole('button',{name:'Выбрать блюдо',exact:true}).nth(1).click();await expect(page.getByRole('dialog').getByText('Состав блюда',{exact:true})).toBeVisible();await expect(page.getByRole('dialog').locator('img')).toHaveJSProperty('complete',true);await page.keyboard.press('Escape');
 await openWaiterWorkspace(page);await page.getByRole('button',{name:'Меню для показа гостю',exact:true}).click();await expect(page.locator('.staff-product img')).toHaveCount(16);await page.getByLabel('Поиск в меню сотрудника',{exact:true}).fill('Рибай');await page.getByRole('button',{name:'Фото и состав',exact:true}).click();await expect(page.getByRole('dialog').getByText(/Говяжий рибай, сливочное масло/)).toBeVisible();await page.keyboard.press('Escape');
 await page.goto('/demo/admin');await page.getByRole('button',{name:'Меню',exact:true}).click();await expect(page.locator('.admin-content .dish-image')).toHaveCount(16);await page.getByRole('button',{name:'Показать фото и состав',exact:true}).nth(15).click();await expect(page.getByRole('dialog').getByText(/Эспрессо, молоко/)).toBeVisible();
});

test('waiter order joins the current session and leaves the guest cart intact',async({page,context})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/demo/guest/home');await page.getByRole('button',{name:'Сканировать QR стола №12',exact:true}).click();await page.getByRole('button',{name:'Меню',exact:true}).click();await page.getByRole('button',{name:'Выбрать блюдо',exact:true}).first().click();await page.getByRole('button',{name:'В корзину',exact:true}).click();
 const waiter=await context.newPage();await waiter.setViewportSize({width:390,height:844});await openWaiterWorkspace(waiter);await waiter.getByRole('button',{name:'Оформить заказ за гостя',exact:true}).click();await waiter.getByLabel('Гость для заказа',{exact:true}).selectOption({label:'Гость 1'});await waiter.getByLabel('Поиск в меню сотрудника',{exact:true}).fill('Рибай');await waiter.getByRole('button',{name:'Фото и состав',exact:true}).click();await expect(waiter.getByRole('button',{name:'Добавить в заказ официанта',exact:true})).toBeDisabled();await waiter.getByRole('radio',{name:/Medium/}).check();await waiter.getByLabel('Количество порций',{exact:true}).fill('2');await waiter.getByLabel('Пожелания к блюду',{exact:true}).fill('Без соли');await waiter.getByRole('button',{name:'Добавить в заказ официанта',exact:true}).click();await waiter.getByRole('button',{name:'Оформить заказ официантом',exact:true}).click();await expect(waiter.locator('.order-item').filter({hasText:'Стейк рибай × 2'})).toBeVisible();await waiter.getByRole('button',{name:'Подтвердить iiko',exact:true}).click();
 await page.getByRole('button',{name:/^Заказ/}).click();await expect(page.getByText('Буррата с томатами',{exact:true})).toBeVisible();await expect(page.getByText('× 1',{exact:true})).toBeVisible();await expect(page.locator('.order-item').filter({hasText:'Стейк рибай × 2'})).toBeVisible();await expect(page.getByText('Принят кухней',{exact:true})).toBeVisible();
 const admin=await context.newPage();await admin.goto('/demo/admin');await expect(admin.locator('.order-item').filter({hasText:'Стейк рибай × 2'})).toBeVisible();
 await page.getByRole('button',{name:'Счёт',exact:true}).click();await expect(page.getByRole('heading',{name:'Разделение счёта',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Свои позиции',exact:true})).toBeVisible();await page.screenshot({path:'.test-runtime/split-collapsed.png',fullPage:true});await expect(page.getByRole('heading',{name:'Разделение счёта',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Свои позиции',exact:true})).toBeVisible();await page.getByRole('button',{name:'Свои позиции',exact:true}).click();await page.getByRole('radio',{name:'Онлайн',exact:true}).click();await page.getByRole('button',{name:'Симулировать успешную оплату',exact:true}).click();await expect(page.getByText('Оплачен',{exact:true})).toBeVisible();
 expect(await waiter.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('waiter opens a free table without guest registration',async({page})=>{
 await openWaiterWorkspace(page);await page.getByRole('button',{name:'Оформить заказ за гостя',exact:true}).click();await page.getByLabel('Стол для заказа',{exact:true}).selectOption('7');await page.getByLabel('Имя или обозначение гостя',{exact:true}).fill('Гость у окна');await page.getByLabel('Поиск в меню сотрудника',{exact:true}).fill('Буррата');await page.getByRole('button',{name:'Фото и состав',exact:true}).click();await page.getByRole('button',{name:'Добавить в заказ официанта',exact:true}).click();await page.getByRole('button',{name:'Оформить заказ официантом',exact:true}).click();await expect(page.getByText('Стол 7 · Гость у окна',{exact:true})).toBeVisible();await page.goto('/demo/admin');await page.getByRole('button',{name:'Зал и столы',exact:true}).click();await expect(page.locator('.table-card').filter({has:page.getByRole('heading',{name:'Стол 7',exact:true})})).toContainText('1 гостей');
});

test('nearby map markers open venue details, including when map tiles are offline',async({page})=>{
 await page.route('https://tile.openstreetmap.org/**',route=>route.abort());await page.setViewportSize({width:360,height:800});await page.goto('/demo/guest/nearby');await expect(page.locator('.welcome-card')).toHaveCount(0);await expect(page.locator('.leaflet-container')).toBeVisible();await expect(page.locator('.mira-map-pin')).toHaveCount(6);await page.getByRole('button',{name:'Открыть MIRA Restaurant',exact:true}).click();await page.getByRole('button',{name:'Открыть заведение',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog').locator('.leaflet-container')).toBeVisible();await expect(page.getByRole('dialog').getByText('Демо-карта Москвы · расположение заведений условное.',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.test-runtime/venue-map-offline.png',fullPage:true});
});
