import {test,expect} from '@playwright/test';
import {getGuestThemePreset,validateGuestTheme} from '../../lib/guest-theme';
const presets=['classic','dark','light'] as const;
test('all approved Theme Lab presets pass semantic contrast validation',()=>{for(const id of presets)for(const result of validateGuestTheme(getGuestThemePreset(id)))expect(result.pass,`${id}: ${result.label} ${result.ratio}`).toBe(true)});
test('all Theme Lab presets preserve guest geometry and domain state at 390px',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/demo/guest/home');await page.getByRole('button',{name:'Сканировать QR стола №12',exact:true}).click();await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(2500);
 const selectors=['.guest-header','.restaurant-hero','.guest-quick-actions','.guest-promo','.popular-grid','.bottom-nav'];
 const geometry=()=>page.evaluate(sels=>sels.map(sel=>{const r=document.querySelector(sel)!.getBoundingClientRect();return [r.width,r.height,r.x,r.y].map(n=>Math.round(n))}),selectors);
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));const before=await geometry();const state=await page.evaluate(()=>localStorage.getItem('mira-link-demo-v1'));
 for(const id of presets){const palette=getGuestThemePreset(id);await page.evaluate(selection=>{localStorage.setItem('mira-demo-guest-theme',JSON.stringify(selection));window.dispatchEvent(new Event('mira-theme'))},{preset:id,palette});await expect(page.locator('.guest-theme').first()).toHaveAttribute('data-theme',id);await page.waitForTimeout(240);expect(await geometry(),id).toEqual(before);expect(await page.evaluate(()=>localStorage.getItem('mira-link-demo-v1'))).toBe(state);expect(await page.locator('.popular-grid img').first().evaluate(el=>getComputedStyle(el).filter)).toBe('none');}
 await expect(page.locator('.guest-quick-actions>button')).toHaveCount(8);expect(await page.locator('.guest-quick-actions>button').evaluateAll(els=>new Set(els.map(e=>e.getBoundingClientRect().y)).size)).toBe(2);await expect(page.getByRole('navigation',{name:'Основная навигация гостя'})).toContainText('Главная');
});
for(const width of [320,480])test(`guest viewport ${width}px and fixed navigation`,async({page})=>{await page.setViewportSize({width,height:844});await page.goto('/demo/guest/home');await page.getByRole('button',{name:'Сканировать QR стола №12',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const nav=await page.locator('.bottom-nav').boundingBox();expect(nav!.x).toBeGreaterThanOrEqual(0);expect(nav!.x+nav!.width).toBeLessThanOrEqual(width);expect(nav!.y+nav!.height).toBe(844);await expect(page.locator('.guest-quick-actions>button')).toHaveCount(8)});
test('Theme Lab applies live, persists, and themes Guest portals',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/demo/guest/home');await page.locator('.demo-mobile-navigation').getByText('Демо режимы',{exact:true}).click();await page.getByRole('button',{name:'Внешний вид'}).click();await page.getByLabel('Пресет темы',{exact:true}).selectOption('light');await expect(page.locator('.guest-theme').first()).toHaveAttribute('data-theme','light');await page.getByRole('button',{name:'Close'}).click();await page.reload();await expect(page.locator('.guest-theme').first()).toHaveAttribute('data-theme','light');await page.getByRole('button',{name:'Меню — быстрое действие'}).click();await page.getByRole('button',{name:/Подробнее/}).first().click();expect(await page.getByRole('dialog').evaluate(el=>getComputedStyle(el).getPropertyValue('--surface').trim())).toBe('#FFFDF7');expect(await page.getByRole('dialog').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(255, 253, 247)');
});

test('authenticated user manages dish favorites without a restaurant session; anonymous action opens GST-037',async({page})=>{
 await page.goto('/demo/guest/home');await page.getByRole('button',{name:'В избранное: Буррата с томатами',exact:true}).click();const gate=page.getByRole('dialog',{name:'Войдите в аккаунт'});await expect(gate).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('mira-dish-favorites:u1'))).toBeNull();expect(await page.evaluate(()=>sessionStorage.getItem('mira-guest'))).toBeNull();await gate.getByRole('button',{name:'Войти как Алексей',exact:true}).click();await expect(gate).toBeHidden();expect(await page.evaluate(()=>localStorage.getItem('mira-link-user-v1'))).toBe('u1');expect(await page.evaluate(()=>sessionStorage.getItem('mira-guest'))).toBeNull();expect(await page.evaluate(()=>{const raw=localStorage.getItem('mira-link-demo-v1');if(!raw)return {sessions:0,guests:0};const state=JSON.parse(raw);return {sessions:state.sessions.length,guests:state.guests.length}})).toEqual({sessions:0,guests:0});await page.getByRole('button',{name:'Ещё',exact:true}).click();await page.getByRole('button',{name:'Избранное',exact:true}).click();await expect(page.getByRole('heading',{name:'Буррата с томатами',exact:true})).toBeVisible();await page.getByRole('button',{name:'Фото и состав',exact:true}).click();await expect(page.getByRole('dialog').getByText('Состав блюда',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'В корзину',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Убрать блюдо из избранного',exact:true}).click();await expect(page.getByText('Здесь появятся любимые блюда. Сохраните понравившееся на главной.',{exact:true})).toBeVisible();
});
