'use client';

import {useRef,useState} from 'react';
import {Bell,UserRound,ChevronDown,ChevronLeft,ChevronRight,UtensilsCrossed,ReceiptText,Wallet,Tag,Heart,BatteryCharging,Car,ArrowRight,Wifi} from 'lucide-react';
import type {Product,CartItem} from '@/lib/domain/model';
import {defaultBrand,type BrandConfig} from '@/lib/guest-theme';
import {Button,Card,IconButton} from '@/components/design-system';
import {guestProductionMode} from '@/components/guest/adapters/status';
import headerStyles from './guest-header.module.css';
import {ProductImage} from './mira-domain-ui';
import {menuPresentation} from '@/lib/menu-presentation';

const money=(value:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',minimumFractionDigits:0,maximumFractionDigits:2}).format(value/100);

export function GuestHeader({tableId,navigate,unread=false,onTable}:{tableId?:string;navigate:(page:string)=>void;unread?:boolean;onTable:()=>void}){return <header className="guest-header"><div className={`guest-logo ${headerStyles.logo}`}><div className={headerStyles.lockup}><img className={headerStyles.monogram} src="/brand/mira-monogram.svg" alt="Монограмма MIRA LINK" draggable={false}/><span>MIRA LINK</span></div></div><div className="guest-header-controls">{tableId&&<button className="table-selector" onClick={onTable} aria-label={`Текущий стол ${tableId}`}><UtensilsCrossed/><span>Стол {tableId}</span><ChevronDown/></button>}<IconButton mode={guestProductionMode} variant="ghost" aria-label="Уведомления" onClick={()=>navigate('notifications')}><Bell/>{unread&&<i className="unread-dot"/>}</IconButton><IconButton mode={guestProductionMode} variant="ghost" aria-label="Профиль" onClick={()=>navigate('profile')}><UserRound/></IconButton></div></header>}

export function RestaurantHero({brand=defaultBrand}:{brand?:BrandConfig}){const [slide,setSlide]=useState(0);const touch=useRef<number|null>(null);const move=(delta:number)=>setSlide(n=>(n+delta+brand.heroImages.length)%brand.heroImages.length);return <section className="restaurant-hero" aria-label="Ресторан" onTouchStart={e=>{touch.current=e.touches[0].clientX}} onTouchEnd={e=>{if(touch.current!==null){const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>40)move(delta<0?1:-1)}touch.current=null}}><img src={brand.heroImages[slide]} alt={`${brand.restaurantName} · ${slide+1}`} draggable={false}/><div className="restaurant-hero-copy"><span>РЕСТОРАН</span><h2>{brand.restaurantName}</h2><p>{brand.marketingContent[slide%brand.marketingContent.length]}</p></div><div className="hero-paging"><span>{slide+1}/{brand.heroImages.length}</span><button aria-label="Предыдущий слайд" onClick={()=>move(-1)}><ChevronLeft/></button><button aria-label="Следующий слайд" onClick={()=>move(1)}><ChevronRight/></button></div></section>}

export const quickActions=[['menu','Меню','Блюда и напитки',UtensilsCrossed],['order','Заказ','Ваши позиции',ReceiptText],['bill','Счёт','Оплата за столом',Wallet],['waiter','Официант','Команда рядом',Bell],['promotions','Акции','Спецпредложения',Tag],['wifi','Wi-Fi','Сеть заведения',Wifi],['powerbank','Пауэрбанк','Зарядка рядом',BatteryCharging],['taxi','Такси','Поездка домой',Car]] as const;

export function GuestHome({products,navigate,onProduct,promotion,favorites,onFavorite}:{products:Product[];navigate:(page:string)=>void;onProduct:(p:Product)=>void;promotion?:string;favorites:string[];onFavorite:(id:string)=>void}){return <><RestaurantHero/><nav className="guest-quick-actions" aria-label="Быстрые действия">{quickActions.map(([page,title,caption,Icon])=><button key={page} aria-label={title==='Меню'?'Меню — быстрое действие':title} onClick={()=>navigate(page)}><Icon/><span>{title}</span><small>{caption}</small></button>)}</nav><button type="button" className="guest-promo guest-promo-banner" aria-label="Посмотреть рекламное предложение" onClick={()=>navigate('promotions')}><img src={defaultBrand.promoImages[0]} alt=""/><span className="guest-promo-banner-shade" aria-hidden="true"/><span className="guest-promo-banner-copy"><small>СПЕЦИАЛЬНОЕ ПРЕДЛОЖЕНИЕ</small><strong>{promotion??'Больше приятных моментов'}</strong></span><span className="promo-action" aria-hidden="true"><ArrowRight/></span></button><section className="guest-popular"><div className="row"><h2>Популярное</h2><Button size="l" mode={guestProductionMode} variant="ghost" onClick={()=>navigate('menu')}>Смотреть всё →</Button></div><div className="popular-grid" aria-label="Популярное">{products.slice(0,6).map(p=><Card key={p.id} mode={guestProductionMode} className="home-popular-card"><div className="home-popular-media"><img src={menuPresentation(p).image} alt=""/><IconButton mode={guestProductionMode} className="home-popular-favourite" aria-label={`В избранное: ${p.name}`} aria-pressed={favorites.includes(p.id)} onClick={()=>onFavorite(p.id)}><Heart/></IconButton></div><div className="home-popular-body"><h3>{p.name}</h3><strong>{p.weight} · {money(p.price)}</strong><Button size="l" mode={guestProductionMode} className="home-popular-action" fullWidth disabled={p.stopped} onClick={()=>onProduct(p)}>{p.stopped?'Недоступно':'Выбрать'}</Button></div></Card>)}</div></section></>}

export function FloatingCart({cart,products,navigate}:{cart:CartItem[];products:Product[];navigate:(page:string)=>void}){if(!cart.length)return null;const first=products.find(p=>p.id===cart[0].productId);const total=cart.reduce((sum,i)=>{const p=products.find(p=>p.id===i.productId);return sum+(p?(p.price+p.modifiers.filter(m=>i.modifierIds.includes(m.id)).reduce((n,m)=>n+m.price,0))*i.quantity:0)},0);return <Card mode={guestProductionMode} className="floating-cart" aria-label="Корзина"><div>{first&&<ProductImage product={first}/>}</div><div><strong>Ваш заказ</strong><small>{cart.reduce((n,i)=>n+i.quantity,0)} поз. · {money(total)}</small></div><Button size="l" mode={guestProductionMode} onClick={()=>navigate('order')}>Оформить →</Button></Card>}
