'use client';
import {useGuestTheme} from './guest-theme';
import {themeStyle} from '@/lib/guest-theme';
import type {ButtonHTMLAttributes,ReactNode,InputHTMLAttributes,SelectHTMLAttributes} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Home,MapPin,CalendarDays,Tag,Grid2X2,QrCode,Search,Inbox,LoaderCircle,Check,Clock,AlertCircle,ArrowUpRight,UtensilsCrossed,Wallet,Bell,UserRound,LayoutDashboard,Table2,Settings,Heart,Ticket,Users,ChartNoAxesCombined,Plug,Building2,ReceiptText,Radio} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from './ui/sheet';
import {Switch} from './ui/switch';
import {formatMoney,labels} from '@/lib/domain/selectors';
export function MiraButton({children,className='',loading=false,disabled,type='button',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{loading?:boolean}){return <button type={type} className={`button ${className}`} disabled={disabled||loading} aria-busy={loading||undefined} {...props}><span className="button-label" style={loading?{visibility:'hidden'}:undefined}>{children}</span>{loading&&<LoaderCircle className="spin button-spinner" size={17} aria-hidden="true"/>}</button>}
export function MiraIconButton(props:ButtonHTMLAttributes<HTMLButtonElement>&{'aria-label':string}){return <MiraButton {...props} className={`icon-button outline ${props.className??''}`}/>}
export function MiraCard({children,className=''}:{children:ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
export function MiraInput({label,...props}:InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="field">{label}<input {...props}/></label>}
export function MiraToggle({label,checked,onChange,disabled=false}:{label:string;checked:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <label className="toggle"><span>{label}</span><Switch aria-label={label} checked={checked} disabled={disabled} onCheckedChange={onChange}/></label>}
export function MiraStatusBadge({status}:{status:string}){const Icon=['error','failed','force_closed_with_balance'].includes(status)?AlertCircle:['succeeded','paid','completed','served','confirmed'].includes(status)?Check:Clock;return <span className={`badge ${status}`}><Icon size={13} aria-hidden="true"/>{labels[status]??status}</span>}
export function MiraMoney({value}:{value:number}){return <span className="money">{formatMoney(value)}</span>}
export function MiraEmptyState({children}:{children:ReactNode}){return <div className="empty"><Inbox size={26} strokeWidth={1.25} aria-hidden="true"/><span>{children}</span></div>}
export function MiraModal({title,description,open,onClose,children}:{title:string;description?:string;open:boolean;onClose:()=>void;children:ReactNode}){const theme=useGuestTheme();return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={`mira-modal ${theme?'guest-theme':''}`} data-mode={theme?.mode} data-theme={theme?.themeId} overlayStyle={theme?{background:theme.colors.overlay}:undefined} style={theme?themeStyle(theme):undefined}><DialogTitle>{title}</DialogTitle><DialogDescription>{description??'Демонстрационный режим MIRA LINK'}</DialogDescription>{children}</DialogContent></Dialog>}
export function MiraBottomSheet({title,description,open,onClose,children}:{title:string;description?:string;open:boolean;onClose:()=>void;children:ReactNode}){const theme=useGuestTheme();return <Sheet open={open} onOpenChange={v=>!v&&onClose()}><SheetContent side="bottom" className={`mira-sheet ${theme?'guest-theme':''}`} data-mode={theme?.mode} overlayStyle={theme?{background:theme.colors.overlay}:undefined} style={theme?themeStyle(theme):undefined}><span className="sheet-handle"/><SheetTitle>{title}</SheetTitle><SheetDescription>{description??'MIRA Restaurant'}</SheetDescription>{children}</SheetContent></Sheet>}
export function DemoBadge(){return <span className="demo-badge">ДЕМО · без реальных заказов и платежей</span>}
/** Displays the supplied original monogram through a CSS viewport; no redrawing. */
export function MiraMonogram(){return <span className="mira-monogram" role="img" aria-label="Монограмма MIRA LINK"><img src="/brand/mira-welcome-reference.jpg" alt="" draggable={false}/></span>}
export function Logo(){return <div className="brand"><MiraMonogram/><span>MIRA LINK<small>PEOPLE · TASTE · TECHNOLOGY</small></span></div>}
export function MiraSkeleton(){return <div className="skeleton" aria-label="Загрузка"/>}

export function MiraSearch(props:InputHTMLAttributes<HTMLInputElement>&{label:string}){return <div className="mira-search"><Search size={18} aria-hidden="true"/><MiraInput {...props}/></div>}
export function MiraSelect({label,children,...props}:SelectHTMLAttributes<HTMLSelectElement>&{label:string}){return <label className="field">{label}<select aria-label={label} {...props}>{children}</select></label>}
export function MiraChip({selected,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{selected?:boolean}){return <MiraButton className={`chip ${selected?'selected':'outline'}`} aria-pressed={selected} {...props}>{children}</MiraButton>}
export function MiraToast({children,kind='info'}:{children:ReactNode;kind?:'info'|'success'|'error'}){if(!children)return null;const Icon=kind==='success'?Check:kind==='error'?AlertCircle:Bell;return <div className={`feedback feedback-${kind}`} role="status" aria-live="polite"><Icon size={16} aria-hidden="true"/><span>{children}</span></div>}
export function MiraTopBar({children}:{children:ReactNode}){return <header className="demo-header">{children}</header>}
const navIcons:Record<string,typeof Home>={home:Home,nearby:MapPin,qr:QrCode,events:CalendarDays,more:Grid2X2};
export function MiraBottomNavigation({items,active,onChange,onPrimaryAction}:{items:string[][];active:string;onChange:(key:string)=>void;onPrimaryAction:()=>void}){return <nav className="bottom-nav" aria-label="Основная навигация гостя">{items.map(([id,label])=>{const Icon=navIcons[id]??Grid2X2;if(id==='qr')return <div className="bottom-nav-action-slot" key={id}><button type="button" className="bottom-nav-qr-fab" aria-label="Сканировать QR" onClick={onPrimaryAction}><span className="bottom-nav-qr-circle" aria-hidden="true"><Icon strokeWidth={1.8}/></span><span className="bottom-nav-qr-label">{label}</span></button></div>;return <button type="button" key={id} aria-current={active===id?'page':undefined} onClick={()=>onChange(id)}><Icon size={24} strokeWidth={1.8} aria-hidden="true"/><span>{label}</span></button>})}</nav>}
export function MiraNavIcon({label}:{label:string}){const icons:Record<string,typeof Home>={'Уведомления':Bell,'Главная':Home,'Меню':UtensilsCrossed,'Заказ':ReceiptText,'Счёт':Wallet,'Официант':Bell,'Обзор':LayoutDashboard,'Операции':Radio,'Заказы':ReceiptText,'Зал и столы':Table2,'Бронирования':CalendarDays,'Сотрудники':Users,'Гости':UserRound,'Лояльность':Heart,'Акции':Tag,'Промокоды':Ticket,'Отзывы':Heart,'Платежи':Wallet,'Чаевые':Heart,'Аналитика':ChartNoAxesCombined,'Коммуникации':Bell,'Интеграции':Plug,'Тариф':ReceiptText,'Настройки':Settings,'Сеть':Building2};const Icon=icons[label]??ArrowUpRight;return <Icon size={18} strokeWidth={1.5} aria-hidden="true"/>}
export function BrandLines(){return <svg className="brand-lines" viewBox="0 0 600 500" fill="none" aria-hidden="true"><path d="M700 30C290-170 660 480 180 510M680 65C310-130 630 445 165 500M660 100C330-90 600 410 150 490M640 135C350-50 570 375 135 480"/></svg>}
