export type ExecutionStatus='created'|'submitted'|'accepted'|'in_progress'|'ready'|'served'|'completed'|'cancelled'|'error';
export type FinancialStatus='unpaid'|'partially_paid'|'paid'|'refund_pending'|'partially_refunded'|'refunded'|'force_closed_with_balance';
export type Organization={id:string;name:string};
export type VenueWifi={ssid:string;password:string;security:'WPA'|'WPA2'|'WEP'|'nopass';hidden?:boolean};
export type Venue={id:string;organizationId:string;name:string;cashbackRate:number;bonusLimit:number;wifi:VenueWifi;timeZone?:string};
export type Zone={id:string;venueId:string;name:string};
export type Table={id:number;zoneId:string;waiterId:string};
export type EmployeeRole='waiter'|'admin';
export type VenueAccess={venueId:string};
export type Employee={id:string;name:string;organizationId:string;venueAccess:VenueAccess[];roles:EmployeeRole[];status:'active'|'inactive';/** @deprecated Stage 7 compatibility only. Use roles. */role:EmployeeRole;/** @deprecated display-only legacy fixture. Use Shift. */shift:string;/** @deprecated derived legacy assignment. Use ShiftAssignment. */tables:number[]};
export type EmployeeAuthContext={id:string;employeeId:string;activeVenueId:string;status:'authenticated';createdAt:string};
export type Shift={id:string;employeeId:string;venueId:string;startedAt:string;endedAt?:string;status:'open'|'closed'};
export type ShiftAssignment={shiftId:string;zoneIds:string[];tableIds:number[]};
export type OperationalActorContext={authContextId:string;shiftId:string;employeeId:string;venueId:string};
export type Modifier={id:string;name:string;price:number;group:string;required:boolean};
export type Product={image?:string;id:string;name:string;category:string;description:string;ingredients:string;weight:string;price:number;stopped:boolean;modifiers:Modifier[]};
export type Guest={id:string;guestSessionId:string;sessionId:string;name:string;userId?:string};
export type User={id:string;name:string;bonusBalance:number;marketing:boolean};
export type Session={id:string;tableId:number;guestIds:string[];closed:boolean;executionStatus:ExecutionStatus;financialStatus:FinancialStatus;createdAt:string;closedAt?:string;forceClosedBalance?:number};
export type CartItem={productId:string;quantity:number;modifierIds:string[];comment:string};
export type OrderItem={id:string;guestId:string;productId:string;name:string;quantity:number;unitPriceSnapshot:number;modifierPriceSnapshot:number;modifiers:string[];comment:string};
export type Order={placedByWaiterId?:string;placedByShiftId?:string;placedByVenueId?:string;posEmployeeId?:string;posShiftId?:string;id:string;sessionId:string;guestId:string;items:OrderItem[];executionStatus:ExecutionStatus;createdAt:string;idempotencyKey:string};
export type Allocation={itemId:string;amount:number};
export type PaymentPart={id:string;sessionId:string;guestId:string;allocations:Allocation[];amount:number;status:'reserved'|'paid'|'released'};
export type Split={id:string;sessionId:string;partIds:string[];mode:string};
export type Payment={id:string;partId:string;sessionId:string;guestId:string;userId?:string;method:'online'|'cash';status:'pending'|'succeeded'|'failed';base:number;promotion:number;promoCode:number;bonuses:number;tips:number;commission:number;tipCommission:number;guestPaysCommission:boolean;total:number;cashback:number;waiterId:string;cashConfirmedByEmployeeId?:string;cashConfirmedByShiftId?:string;createdAt:string};
export type FinancialSplit={paymentId:string;venueShare:number;waiterTipShare:number;tipCommissionShare:number;miraCommissionShare:number;venueCommissionLiability:number};
export type AdditionalTip={id:string;key:string;guestId:string;waiterId:string;tip:number;commission:number;guestPaysCommission:boolean;total:number;waiterShare:number};
export type StaffCall={id:string;sessionId?:string;tableId:number;guestId?:string;type:'waiter'|'admin';status:'created'|'accepted'|'completed'|'cancelled';createdAt:string;acceptedAt?:string;acceptedByEmployeeId?:string;acceptedByShiftId?:string;completedByEmployeeId?:string;completedByShiftId?:string;cancelledAt?:string};
export type Notification={id:string;userId?:string;guestId?:string;type:'service'|'marketing';message:string};
export type BonusTransaction={id:string;userId:string;paymentId:string;amount:number;type:'accrual'|'redemption'|'refund'};
export type Booking={id:string;venueId:string;date:string;time:string;guests:number;requirements:string;comment:string;status:'confirmed'|'cancelled'};
export type Review={id:string;sessionId:string;userId:string;rating:number;text:string};
export type PromotionType='discount'|'combo'|'gift'|'other'|'event';
export type Promotion={
 id:string;
 title:string;
 description:string;
 published:boolean;
 venueId?:string;
 type?:PromotionType;
 image?:string;
 shortDescription?:string;
 benefit?:string;
 price?:number;
 oldPrice?:number;
 startAt?:string;
 endAt?:string;
 validity?:string;
 timeWindow?:string;
 minimumOrder?:number;
 eligibleProductIds?:string[];
 eligibleCategories?:string[];
 featured?:boolean;
 conditions?:string[];
};
export type PromoCode={id:string;code:string;description:string;enabled:boolean};
export type Refund={id:string;paymentId:string;amount:number;status:'pending'|'completed'};
export type Event={id:string;type:string;at:string;detail:string};
/** Venue-facing catalogue content. Kept separate from Event, which is the operational audit log. */
export type VenueEvent={id:string;venueId:string;title:string;description:string;category:string;startsAt:string;published:boolean;endsAt?:string;image?:string;shortDescription?:string;locationLabel?:string;demo?:boolean};
export type PowerbankRental={id:string;guestId?:string;status:'active'|'returned'};
export type DeliveryOrder={id:string;guestId?:string;address:string;items:string;status:'created'};
export type State={version:2;revision:number;seq:number;organizations:Organization[];venue:Venue;zones:Zone[];tables:Table[];employees:Employee[];employeeAuthContexts:EmployeeAuthContext[];shifts:Shift[];shiftAssignments:ShiftAssignment[];products:Product[];sessions:Session[];guests:Guest[];users:User[];carts:Record<string,CartItem[]>;orders:Order[];splits:Split[];parts:PaymentPart[];payments:Payment[];financialSplits:FinancialSplit[];additionalTips:AdditionalTip[];calls:StaffCall[];notifications:Notification[];bonusTransactions:BonusTransaction[];bookings:Booking[];reviews:Review[];promotions:Promotion[];venueEvents:VenueEvent[];promoCodes:PromoCode[];refunds:Refund[];events:Event[];config:{commissionRate:number;tipCommissionRate:number;additionalTipCommissionRate:number;demoMode:boolean};simulator:{delay:number;posError:boolean};rentals:PowerbankRental[];deliveries:DeliveryOrder[];favorites:string[]};
export type CommonOrder={sessionId:string;items:OrderItem[];total:number};
export type Bill={sessionId:string;total:number;paid:number;unpaidBalance:number;financialStatus:FinancialStatus};
export type Menu=Product[]; export type Category=string; export type Waiter=OperationalActorContext; export type Role=EmployeeRole; export type Tip=Pick<Payment,'id'|'tips'|'guestId'>; export type PlatformCommission=Pick<FinancialSplit,'miraCommissionShare'|'venueCommissionLiability'>; export type BonusAccount=Pick<User,'id'|'bonusBalance'>; export type POSState=State['simulator'];

export type AnalyticsState={revenue:number;sessions:number;orders:number;averageCheck:number;activeTables:number;online:number;cash:number;initialTips:number;additionalTips:number;bonusesAccrued:number;bonusesRedeemed:number;staffCalls:number;errors:number};
