import type {State,Product} from './model';
const dishes:[string,string,number,string][]=[['Буррата с томатами','Закуски',890,'220 г'],['Тартар из говядины','Закуски',980,'180 г'],['Карпаччо из лосося','Закуски',1090,'160 г'],['Зелёный салат','Салаты',690,'240 г'],['Салат с креветками','Салаты',940,'260 г'],['Тёплый салат с уткой','Салаты',990,'250 г'],['Тыквенный крем-суп','Супы',590,'300 г'],['Том ям','Супы',890,'350 г'],['Ризотто с грибами','Горячее',990,'280 г'],['Паста с креветками','Горячее',1190,'300 г'],['Стейк рибай','Горячее',2890,'320 г'],['Лосось на гриле','Горячее',1690,'280 г'],['Баскский чизкейк','Десерты',590,'150 г'],['Шоколадный фондан','Десерты',640,'170 г'],['Лимонад юдзу','Напитки',390,'400 мл'],['Капучино','Напитки',290,'250 мл']];
export const seed=():State=>({
 version:2,revision:0,seq:0,
 organizations:[{id:'org-mira',name:'MIRA LINK Demo Organization'}],
 venue:{id:'mira',organizationId:'org-mira',name:'MIRA Restaurant',cashbackRate:0.05,bonusLimit:0.5,wifi:{ssid:'MIRA_GUEST',password:'mira2026',security:'WPA'}},
 zones:[{id:'zone-main',venueId:'mira',name:'Основной зал'},{id:'zone-terrace',venueId:'mira',name:'Терраса'}],
 tables:Array.from({length:12},(_,i)=>({id:i+1,zoneId:i<6?'zone-main':'zone-terrace',waiterId:i<6?'w2':'w1'})),
 employees:[
  {id:'w1',name:'Александр',organizationId:'org-mira',venueAccess:[{venueId:'mira'}],roles:['waiter'],status:'active',role:'waiter',shift:'12:00–00:00',tables:[7,8,9,10,11,12]},
  {id:'w2',name:'Мария',organizationId:'org-mira',venueAccess:[{venueId:'mira'}],roles:['waiter'],status:'active',role:'waiter',shift:'12:00–00:00',tables:[1,2,3,4,5,6]},
  {id:'a1',name:'Анна',organizationId:'org-mira',venueAccess:[{venueId:'mira'}],roles:['admin'],status:'active',role:'admin',shift:'12:00–00:00',tables:[]},
 ],
 employeeAuthContexts:[],shifts:[],shiftAssignments:[],
 products:dishes.map(([name,category,price,weight],i):Product=>({id:`p${i+1}`,image:i===0?'https://res.cloudinary.com/foodfriends/image/upload/w_600%2Ch_400%2Cc_fill%2Cq_60/restaurant/8d867aef65c31a12495509aeac2692af.png':undefined,name,category,price:price*100,weight,stopped:false,description:'Готовим на нашей кухне из свежих продуктов. Подаём сразу после приготовления.',ingredients:i===0?'Буррата, томаты, базилик, оливковое масло':'Состав и аллергены уточняйте у официанта',modifiers:i===10?[{id:'rare',name:'Rare',price:0,group:'Прожарка',required:true},{id:'medium',name:'Medium',price:0,group:'Прожарка',required:true},{id:'well',name:'Well done',price:0,group:'Прожарка',required:true}]:i===15?[{id:'oat',name:'Овсяное молоко',price:8000,group:'Молоко',required:false}]:[{id:'extra',name:'Дополнительный соус',price:9000,group:'Дополнения',required:false}]})),
 sessions:[],guests:[],users:[{id:'u1',name:'Алексей',bonusBalance:150000,marketing:true}],carts:{},orders:[],splits:[],parts:[],payments:[],financialSplits:[],additionalTips:[],calls:[],notifications:[],bonusTransactions:[],bookings:[],reviews:[],promotions:[{id:'pr1',title:'Вечер в MIRA',description:'Сезонное меню и живая музыка по пятницам. Условия уточняйте у команды ресторана.',published:true},{id:'pr2',title:'Ваш особенный день',description:'Расскажите о поводе при бронировании — команда подготовит стол.',published:true}],promoCodes:[],refunds:[],events:[],config:{commissionRate:0,additionalTipCommissionRate:0,demoMode:true},simulator:{delay:400,posError:false},rentals:[],deliveries:[],favorites:[]
});
export const lifestyleEvents=[{id:'jazz',title:'Джаз. Вино. Хороший вечер.',date:'Пятница · 20:00',description:'Акустический джаз в MIRA Restaurant. Демонстрационное событие.'},{id:'chef',title:'Ужин с шефом',date:'Суббота · 19:00',description:'Знакомство с сезонным меню. Демонстрационное событие.'}];
export const nearbyVenues=[{id:'mira',name:'MIRA Restaurant',category:'Современная кухня',distance:'120 м',rating:'4,9',hours:'12:00–00:00'},{id:'garden',name:'Garden Café',category:'Кофе и завтраки',distance:'450 м',rating:'4,8',hours:'08:00–22:00'},{id:'atelier',name:'Atelier',category:'Авторская кухня',distance:'800 м',rating:'4,7',hours:'13:00–23:00'}];
