import type {State,OrderItem,Bill,CommonOrder} from './model';
export const formatMoney=(v:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2}).format(v/100);
export const calculateTipCommission=(s:State,tips:number)=>Math.round(tips*s.config.tipCommissionRate);
export const calculatePaymentQuote=(s:State,{orderAmount,tips,bonuses,guestPaysTipCommission}:{orderAmount:number;tips:number;bonuses:number;guestPaysTipCommission:boolean})=>{
 const tipCommission=calculateTipCommission(s,tips);
 return {orderAmount,tips,tipCommission,bonuses,guestPayable:orderAmount-bonuses+tips+(guestPaysTipCommission?tipCommission:0),waiterNetTip:tips-(guestPaysTipCommission?0:tipCommission)};
};
export const itemTotal=(i:OrderItem)=>(i.unitPriceSnapshot+i.modifierPriceSnapshot)*i.quantity;
export const calculateCommonOrder=(s:State,id:string):CommonOrder=>{const items=s.orders.filter(o=>o.sessionId===id&&o.executionStatus!=='cancelled').flatMap(o=>o.items);return {sessionId:id,items,total:items.reduce((a,i)=>a+itemTotal(i),0)}};
export const calculateBill=(s:State,id:string):Bill=>{const total=calculateCommonOrder(s,id).total;const paid=s.payments.filter(p=>p.sessionId===id&&p.status==='succeeded').reduce((a,p)=>a+p.base,0);const session=s.sessions.find(x=>x.id===id);return {sessionId:id,total,paid,unpaidBalance:Math.max(0,total-paid),financialStatus:session?.forceClosedBalance?'force_closed_with_balance':paid>=total&&total>0?'paid':paid>0?'partially_paid':'unpaid'}};
export const calculateUnpaidBalance=(s:State,id:string)=>calculateBill(s,id).unpaidBalance;
export const calculateGuestOwnItems=(s:State,id:string)=>s.orders.filter(o=>o.guestId===id&&o.executionStatus!=='cancelled').flatMap(o=>o.items);
export const remainingItem=(s:State,item:OrderItem,reservations=false)=>itemTotal(item)-s.parts.filter(p=>p.status==='paid'||(reservations&&p.status==='reserved')).flatMap(p=>p.allocations).filter(a=>a.itemId===item.id).reduce((n,a)=>n+a.amount,0);
export const getRevenue=(s:State)=>s.payments.filter(p=>p.status==='succeeded').reduce((n,p)=>n+p.base-p.bonuses-p.promotion-p.promoCode,0)-s.refunds.filter(r=>r.status==='completed').reduce((n,r)=>n+r.amount,0);
export const getPaidAmount=(s:State)=>s.payments.filter(p=>p.status==='succeeded').reduce((n,p)=>n+p.base,0);
export const getUnpaidAmount=(s:State)=>s.sessions.reduce((n,x)=>n+calculateUnpaidBalance(s,x.id),0);
export const getSessionCount=(s:State)=>s.sessions.length;
export const getOrderCount=(s:State)=>s.orders.length;
export const getAverageCheck=(s:State)=>s.sessions.length?Math.round(getRevenue(s)/s.sessions.length):0;
export const calculateAverageCheck=getAverageCheck;
export const getOnlinePaymentsTotal=(s:State)=>s.payments.filter(p=>p.method==='online'&&p.status==='succeeded').reduce((n,p)=>n+p.total,0);
export const getCashPaymentsTotal=(s:State)=>s.payments.filter(p=>p.method==='cash'&&p.status==='succeeded').reduce((n,p)=>n+p.total,0);
export const getInitialTipsTotal=(s:State)=>s.payments.filter(p=>p.status==='succeeded').reduce((n,p)=>n+p.tips,0);
export const getAdditionalTipsTotal=(s:State)=>s.additionalTips.reduce((n,p)=>n+p.tip,0);
export const getBonusesAccrued=(s:State)=>s.bonusTransactions.filter(t=>t.type==='accrual').reduce((n,t)=>n+t.amount,0);
export const getBonusesSpent=(s:State)=>Math.abs(s.bonusTransactions.filter(t=>t.type==='redemption').reduce((n,t)=>n+t.amount,0));
export const labels:Record<string,string>={submitted:'Заказ отправлен',accepted:'Принят кухней',in_progress:'Готовится',ready:'Готово',served:'Подано',completed:'Завершено',cancelled:'Отменено',error:'Ошибка передачи заказа',unpaid:'Не оплачен',partially_paid:'Частично оплачен',paid:'Оплачен',force_closed_with_balance:'Закрыт с задолженностью',pending:'Ожидает подтверждения',succeeded:'Успешно',failed:'Не удалось оплатить',reserved:'Выбрано',released:'Освобождено',created:'Новый вызов',confirmed:'Подтверждено',refund_pending:'Возврат ожидается',refunded:'Возвращено',partially_refunded:'Частично возвращено'};
