import type {Product,Promotion} from './domain/model';
export type Location={latitude:number;longitude:number};
export type VenueImageType='INTERIOR'|'EXTERIOR'|'TERRACE'|'PLACEHOLDER';
export type NearbyVenue=Location&{id:string;name:string;category:string;kind:'restaurant'|'coffee'|'cafe';rating:string;address:string;venueImage:string;venueImageType:VenueImageType;description:string;hours:string;services:string[];promotions:string[];menu:Product[];deliveryEnabled:boolean;bookingEnabled:boolean;distanceMeters:number;distance:string};
export const demoLocation:Location={latitude:55.764,longitude:37.598};
// One demo catalogue drives map, list, details and delivery; addresses are fictional.
const definitions=[
 {id:'mira',name:'MIRA Restaurant',category:'Современная кухня',kind:'restaurant',latitude:55.7637,longitude:37.5975,rating:'4,9',address:'Москва, Тихий переулок, 12 · демо-адрес',venueImage:'/images/mira-restaurant.jpg',venueImageType:'INTERIOR',description:'Современная кухня и неспешные вечера в тёплом ресторанном пространстве.',hours:'12:00–00:00',services:['Wi-Fi','Такси'],promotions:[],menuIds:[],deliveryEnabled:true,bookingEnabled:true},
 {id:'garden',name:'Garden Café',category:'Кофе и завтраки',kind:'coffee',latitude:55.7663,longitude:37.601,rating:'4,8',address:'Москва, Садовая улица, 8 · демо-адрес',venueImage:'/images/venues/garden-cafe.jpg',venueImageType:'INTERIOR',description:'Кофе, десерты и зелёный уголок для встречи с друзьями.',hours:'08:00–22:00',services:['Wi-Fi','Кофе с собой'],promotions:['Сезонная коллекция десертов'],menuIds:['p13','p14','p15','p16'],deliveryEnabled:true,bookingEnabled:false},
 {id:'atelier',name:'Atelier',category:'Авторская кухня',kind:'restaurant',latitude:55.7618,longitude:37.607,rating:'4,7',address:'Москва, Малая улица, 4 · демо-адрес',venueImage:'/images/venues/atelier.jpg',venueImageType:'INTERIOR',description:'Камерный ресторан с авторскими блюдами и вниманием к подаче.',hours:'13:00–23:00',services:['Wi-Fi','Такси'],promotions:['Ужин с шефом по субботам'],menuIds:['p2','p3','p9','p11','p12','p13'],deliveryEnabled:false,bookingEnabled:false},
 {id:'family',name:'Family Kitchen',category:'Семейный ресторан',kind:'restaurant',latitude:55.768,longitude:37.595,rating:'4,9',address:'Москва, Парковый проезд, 6 · демо-адрес',venueImage:'/images/venues/family-kitchen.jpg',venueImageType:'INTERIOR',description:'Знакомые вкусы, просторные столы и уют для всей семьи.',hours:'10:00–23:00',services:['Детское меню','Wi-Fi'],promotions:[],menuIds:['p4','p7','p10','p13','p15'],deliveryEnabled:true,bookingEnabled:false},
 {id:'leaf',name:'Leaf Café',category:'Кафе',kind:'cafe',latitude:55.759,longitude:37.599,rating:'4,6',address:'Москва, Зелёный переулок, 3 · демо-адрес',venueImage:'/images/venues/leaf-cafe.jpg',venueImageType:'INTERIOR',description:'Лёгкие салаты, сезонные овощи и время для себя.',hours:'09:00–21:00',services:['Wi-Fi','С собой'],promotions:['Новое сезонное меню'],menuIds:['p4','p5','p7','p15','p16'],deliveryEnabled:true,bookingEnabled:false},
 {id:'ember',name:'Ember Grill',category:'Гриль-ресторан',kind:'restaurant',latitude:55.771,longitude:37.608,rating:'4,8',address:'Москва, Улица Мастеров, 15 · демо-адрес',venueImage:'/images/venues/ember-grill.jpg',venueImageType:'INTERIOR',description:'Блюда с гриля и ужин с доставкой к вашему столу дома.',hours:'12:00–23:00',services:['Такси','С собой'],promotions:[],menuIds:['p6','p11','p12','p14','p15'],deliveryEnabled:true,bookingEnabled:false}
] as const;
export function distanceMeters(a:Location,b:Location){const rad=(v:number)=>v*Math.PI/180;const dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude);const h=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)))}
export function formatDistance(m:number){return m<1000?`${Math.round(m)} м`:`${(m/1000).toLocaleString('ru-RU',{maximumFractionDigits:1})} км`}
export function getNearbyVenues(products:Product[],promotions:Promotion[],location:Location):NearbyVenue[]{return definitions.map(v=>{const distance=distanceMeters(location,v);return {...v,venueImage:v.venueImage||'/images/venues/mira-link-venue-placeholder.svg',venueImageType:v.venueImageType??'PLACEHOLDER',services:[...v.services],promotions:v.id==='mira'?promotions.filter(p=>p.published).map(p=>p.title):[...v.promotions],menu:v.id==='mira'?products:products.filter(p=>(v.menuIds as readonly string[]).includes(p.id)),distanceMeters:distance,distance:formatDistance(distance)}}).sort((a,b)=>a.distanceMeters-b.distanceMeters)}
export function isVenueOpen(hours:string,now:Date){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(now).split(':').map(Number);const time=parts[0]*60+parts[1];const [start,end]=hours.split('–').map(t=>{const [h,m]=t.split(':').map(Number);return h*60+m});return end<=start?time>=start||time<end:time>=start&&time<end}
